[package]
name = "purs"
version = "0.2.0"
authors = ["Xavier Cambar <xcambar@gmail.com>", "Johan Håkansson <jhakanzon@gmail.com"]
edition = "2018"

[dependencies]
ansi_term = "0.11"
clap = "2.33"
dirs = "2.0"
git2 = "0.8"
regex = "1.1.6"
tico = "1.0.0"
chrono = "0.4.19"
sys-info = "0.7"
